### ISSUE TITLE
[BUG] GPIO实现ATX开关机 有问题？

### ISSUE THREAD

**Issue by 5fh** [mofeng-git/One-KVM#146]
玩客云1.3版刷了Onecloud_250601-1642ce73版本，硬件焊了红外遥控焊盘gpio-420和GND线，开机后，测量红外焊盘接触点，发现一直都有电压(3.23~3.24)，无论网页点击 开关机选项按钮 都有电压，正常的应该为0伏？莫不是修改脚本代码？

**Comment by BG4QBC** [comment]
遇到了相同的问题，在网页上点开关机没反应 gpio-420电压始终为3.3V。直接用命令可以正常控制gpio-420的高低电平
命令行如下
```
gpioset -m time -s 1 gpiochip1 7=0
gpioset gpiochip1 7=1
```

**Comment by BG4QBC** [comment]
搞了一下，是权限和脚本位置变了。解决方法：
修改`/etc/kvmd/override.yaml`配置文件的`GPIO`节点：

```
    gpio:
            short_press:
                type: cmd
                cmd: [/usr/bin/sudo, /etc/kvmd/custom_atx/gpio.sh, short]
            long_press:
                type: cmd
                cmd: [/usr/bin/sudo, /etc/kvmd/custom_atx/gpio.sh, long]
            reset_press:
                type: cmd
                cmd: [/usr/bin/sudo, /etc/kvmd/custom_atx/gpio.sh, reset]
```
