### ISSUE TITLE
OpenWrt 系统下 docker 版本出现 `Failed to import module: systemd.journal`

### ISSUE THREAD

**Issue by OceanApart** [mofeng-git/One-KVM#40]
错误日志如下，访问 Web 端口提示 502 错误，请问是 OpenWrt 环境的问题吗？

```
kvmd  | FileNotFoundError: [Errno 2] No such file or directory
kvmd  | 2024-10-18 14:05:33,847 WARN exited: kvmd (exit status 1; not expected)
kvmd  | 2024-10-18 14:05:34,858 INFO spawned: 'kvmd' with pid 20171
kvmd  | 2024-10-18 14:05:35,862 INFO success: kvmd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
kvmd  | Failed to import module: systemd.journal
^[[Akvmd  | Traceback (most recent call last):
kvmd  |   File "<frozen runpy>", line 198, in _run_module_as_main
kvmd  |   File "<frozen runpy>", line 88, in _run_code
kvmd  |   File "/kvmd/apps/kvmd/__main__.py", line 24, in <module>
kvmd  |     main()
kvmd  |   File "/kvmd/apps/kvmd/__init__.py", line 68, in main
kvmd  |     hid = get_hid_class(config.hid.type)(**hid_kwargs)
kvmd  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kvmd  |   File "/kvmd/plugins/hid/otg/__init__.py", line 63, in __init__
kvmd  |     self.__notifier = aiomulti.AioProcessNotifier()
kvmd  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kvmd  |   File "/kvmd/aiomulti.py", line 62, in __init__
kvmd  |     self.__queue: "multiprocessing.Queue[None]" = multiprocessing.Queue()
kvmd  |                                                   ^^^^^^^^^^^^^^^^^^^^^^^
kvmd  |   File "/usr/local/lib/python3.12/multiprocessing/context.py", line 103, in Queue
kvmd  |     return Queue(maxsize, ctx=self.get_context())
kvmd  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kvmd  |   File "/usr/local/lib/python3.12/multiprocessing/queues.py", line 43, in __init__
kvmd  |     self._rlock = ctx.Lock()
kvmd  |                   ^^^^^^^^^^
kvmd  |   File "/usr/local/lib/python3.12/multiprocessing/context.py", line 68, in Lock
kvmd  |     return Lock(ctx=self.get_context())
kvmd  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kvmd  |   File "/usr/local/lib/python3.12/multiprocessing/synchronize.py", line 169, in __init__
kvmd  |     SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
kvmd  |   File "/usr/local/lib/python3.12/multiprocessing/synchronize.py", line 57, in __init__
kvmd  |     sl = self._semlock = _multiprocessing.SemLock(
kvmd  |                          ^^^^^^^^^^^^^^^^^^^^^^^^^
kvmd  | FileNotFoundError: [Errno 2] No such file or directory
kvmd  | 2024-10-18 14:05:42,848 WARN exited: kvmd (exit status 1; not expected)
kvmd  | 2024-10-18 14:05:43,861 INFO spawned: 'kvmd' with pid 20175
kvmd  | 2024-10-18 14:05:44,865 INFO success: kvmd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

```bash
# uname -a
Linux OpenWrt 6.1.109-flippy-91+o #251 SMP Sun Sep  8 17:23:23 CST 2024 aarch64 GNU/Linu
```

`docker-compose.yaml`

```yaml
services:
  kvmd:
    image: silentwind0/kvmd
    container_name: kvmd
    volumes:
      - /lib/modules:/lib/modules:ro
      - /dev:/dev
      - /sys/kernel/config:/sys/kernel/config
    environment:
      - OTG=1
    ports:
      - 8080:8080
      - 4430:4430
      - 5900:5900
      - 623:623
    privileged: true
```
